spring.application.name=E-Commerce

# Avoid port conflicts while running from IDE/devtools
#server.port=5000



spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect